const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 1,
    },
    tasks: [
      {
        taskTitle: "Fix login bug",
        taskDescription: "Resolve the bug causing login failure on Safari.",
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
        date: "2025-05-25",
        category: "bugfix",
      },
      {
        taskTitle: "Prepare report",
        taskDescription: "Summarize weekly team progress in a document.",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        date: "2025-05-20",
        category: "report",
      },
      {
        taskTitle: "Update contact page",
        taskDescription: "Add company address and phone number.",
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
        date: "2025-05-21",
        category: "frontend",
      },
    ],
  },
  {
    id: 2,
    firstName: "Bhavya",
    email: "employee2@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completedTask: 2,
      failedTask: 1,
    },
    tasks: [
      {
        taskTitle: "Create database schema",
        taskDescription: "Design ER diagram for new project.",
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
        date: "2025-05-25",
        category: "database",
      },
      {
        taskTitle: "Client call",
        taskDescription: "Discuss feature requirements with the client.",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        date: "2025-05-24",
        category: "meeting",
      },
      {
        taskTitle: "Fix email template",
        taskDescription: "Correct alignment in the newsletter template.",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        date: "2025-05-23",
        category: "frontend",
      },
      {
        taskTitle: "Security review",
        taskDescription: "Review code for common vulnerabilities.",
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
        date: "2025-05-22",
        category: "security",
      },
    ],
  },
  {
    id: 3,
    firstName: "Chirag",
    email: "employee3@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 1,
    },
    tasks: [
      {
        taskTitle: "Create landing page",
        taskDescription: "Design and code responsive UI.",
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
        date: "2025-05-25",
        category: "design",
      },
      {
        taskTitle: "Optimize images",
        taskDescription: "Compress images on the homepage.",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        date: "2025-05-21",
        category: "frontend",
      },
      {
        taskTitle: "Slack integration",
        taskDescription: "Add Slack notifications for new leads.",
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
        date: "2025-05-20",
        category: "backend",
      },
    ],
  },
  {
    id: 4,
    firstName: "Divya",
    email: "employee4@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completedTask: 2,
      failedTask: 1,
    },
    tasks: [
      {
        taskTitle: "Write blog post",
        taskDescription: "Explain benefits of our new feature.",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        date: "2025-05-18",
        category: "content",
      },
      {
        taskTitle: "Edit testimonial video",
        taskDescription: "Add subtitles and trim silence.",
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
        date: "2025-05-17",
        category: "media",
      },
      {
        taskTitle: "Newsletter draft",
        taskDescription: "Prepare content for June newsletter.",
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
        date: "2025-05-25",
        category: "marketing",
      },
      {
        taskTitle: "SEO update",
        taskDescription: "Add alt tags and meta descriptions.",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        date: "2025-05-22",
        category: "seo",
      },
    ],
  },
  {
    id: 5,
    firstName: "Esha",
    email: "employee5@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completedTask: 1,
      failedTask: 1,
    },
    tasks: [
      {
        taskTitle: "Deploy backend",
        taskDescription: "Push latest backend changes to production.",
        active: false,
        newTask: false,
        completedTask: true,
        failedTask: false,
        date: "2025-05-19",
        category: "deployment",
      },
      {
        taskTitle: "Test payment gateway",
        taskDescription: "Run integration tests with sandbox mode.",
        active: false,
        newTask: false,
        completedTask: false,
        failedTask: true,
        date: "2025-05-20",
        category: "qa",
      },
      {
        taskTitle: "Fix 404 page",
        taskDescription: "Redesign and link missing pages.",
        active: true,
        newTask: true,
        completedTask: false,
        failedTask: false,
        date: "2025-05-25",
        category: "frontend",
      },
    ],
  },
];

const admin = [
  {
    id: 100,
    firstName: "Rohan",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
